### ISSUE TITLE
[pylogin] A dictionary with language variants

### ISSUE THREAD

**Issue by k8ieone** [k8ieone/rugl#14]
We may be able to do an infinite number of translations like this. This could be applied to any program.

Below code is just an example.
```python
if lang == "cz":
        dictionary{"hello"} = "ahoj"
        dictionary{"world"} = "svět"
else:
        dictionary{"hello"} = "hello"
        dictionary{"world"} = "world"
print (dictionary.get("hello"),dictionary.get("world"))
```

**Comment by satcom886** [comment]
Also there would have to be some mechanism to support inflection (skloňování).
Example would print "ahoj svět" instead of the desired "Ahoj světe!")
